# Site settngs
title :  ''Sitio web de Humanidades Digitales: reflexiones filosóficas y más''
author:
  name: Paulina Michelle Mendoza
  mail: 00paumendoza@gmail.com
description: ''Sitio para el curso de Humanidades Digiates impartido por Ernesto Priani.'' 

# Build settings
remote_theme: jekyll/minima
