#Site settings
title: Sitio del curso Humanidades Digitales por Paulina Mendoza
author:
  name: Paulina Michelle Mnedoza Serrano
  mail: 00paumendoza@gmail.com
description: ''Sitio para el curso de Humanidades Digiates.'' 
